export const INIT_STOCK=[
  {typ:"Étudiant grande école",dispo:true,nb:47,note:"Profil le plus demandé"},
  {typ:"Étudiant université",dispo:true,nb:134,note:"Très disponible toutes zones"},
  {typ:"Professeur EN",dispo:false,nb:3,note:"Stock très limité"},
  {typ:"AESH",dispo:false,nb:1,note:"Recrutement en cours"},
  {typ:"Professeur certifié",dispo:true,nb:12,note:"Disponible Paris/Lyon"},
  {typ:"Formateur",dispo:true,nb:8,note:"En ligne et domicile"},
];
export const INIT_SCRIPTS={
  intro:{title:"Introduction",color:"#16A34A",steps:[{label:"Accroche",text:"Bonjour [Prénom], c'est [Votre prénom] des Sherpas 👋 Avez-vous deux minutes ?"},{label:"Légitimité",text:"Je vous appelle car vous avez demandé des informations sur nos cours particuliers."},{label:"Ordre du jour",text:"Mon objectif est de comprendre votre situation et voir si on peut vous aider. Ça vous convient ?"}]},
  decouverte:{title:"Découverte",color:"#0B68B4",steps:[{label:"Situation",text:"En quelle classe est votre enfant ? Dans quelle(s) matière(s) rencontre-t-il des difficultés ?"},{label:"Problème",text:"Depuis combien de temps observez-vous ces difficultés ?"},{label:"Implication",text:"Est-ce que cela impacte sa confiance en lui ?"},{label:"Besoin",text:"Idéalement, qu'aimeriez-vous voir changer dans les 2-3 prochains mois ?"}]},
  pitch:{title:"Présentation",color:"#7C3AED",steps:[{label:"Solution",text:"Les Sherpas met en relation des élèves avec des professeurs triés sur le volet, issus des meilleures grandes écoles 🎓"},{label:"Différenciation",text:"Nos profs sont sélectionnés à moins de 5% ✨ Compatibilité garantie, changement gratuit si besoin."},{label:"Preuve sociale",text:"Des milliers de familles accompagnées, un taux de satisfaction de 98% ⭐"}]},
  closing:{title:"Closing",color:"#DA4F00",steps:[{label:"Reformulation",text:"Si je résume : vous cherchez un professeur en [matière] pour [prénom], c'est bien ça ?"},{label:"Engagement",text:"On a justement plusieurs profils disponibles. Je peux vous proposer une mise en relation dès cette semaine 🚀"},{label:"Objection finale",text:"Je comprends que vous voulez réfléchir. Qu'est-ce qui vous empêche de vous lancer aujourd'hui ?"},{label:"Closing doux",text:"Parfait ! Je vous envoie un récapitulatif et je vous rappelle [date]. Bonne journée 😊"}]},
};
export const INIT_OBJECTIONS=[
  {id:"prix",color:"#E11D48",icon:"💰",label:"C'est trop cher",ref:"Vous trouvez que le tarif ne correspond pas à vos attentes ?",arg:"Ramené à une heure par semaine, c'est moins qu'un abonnement streaming. Et là on parle de l'avenir scolaire de votre enfant 📚",rebond:"Plutôt que le prix, comparons au résultat : si votre enfant passe de 8 à 14 en maths, qu'est-ce que ça vaut pour vous ?"},
  {id:"qualite",color:"#1E40AF",icon:"🎓",label:"Je préfère un vrai prof",ref:"Vous voulez être sûr que le professeur est vraiment qualifié ?",arg:"Nos Sherpas sont sélectionnés à moins de 5% ✨",rebond:"Un prof qui a réussi le bac il y a 2 ans connaît exactement ce qu'on attend aux examens aujourd'hui."},
  {id:"timing",color:"#DA4F00",icon:"📅",label:"C'est pas le bon moment",ref:"Vous avez l'impression que ce n'est pas urgent ?",arg:"En accompagnement scolaire, le temps est l'ennemi principal. Chaque semaine sans aide, les lacunes s'accumulent.",rebond:"Quel serait le bon moment ? Et qu'est-ce qui se passe si on attend jusqu'à là ?"},
  {id:"concurrence",color:"#0B68B4",icon:"🤝",label:"J'ai déjà quelqu'un",ref:"Vous avez déjà un suivi. Qu'est-ce qui vous a poussé à chercher une autre option ?",arg:"Notre valeur ajoutée : suivi des sessions, remplacement facile, diversité de profils 💪",rebond:"Y a-t-il des matières sans suivi actuellement ?"},
  {id:"reflechir",color:"#71717A",icon:"🤔",label:"Je dois réfléchir",ref:"Quelque chose vous freine encore. Qu'est-ce qui vous manque pour décider ?",arg:"Qu'est-ce qui vous ferait basculer du côté du oui ?",rebond:"Budget, timing ou doutes sur la qualité ?"},
];
export const INIT_FEEDBACKS=[
  {id:1,date:"2026-04-02",auteur:"Julien",  anonyme:false,clientTypes:["Parent stressé"],  objections:["Prix"],           bien:["Découverte client"],bloque:["Closing"],                  confiance:7,suggestions:"Script pour parents comparant avec Superprof."},
  {id:2,date:"2026-04-02",auteur:"Jonathan",anonyme:false,clientTypes:["Parent rationnel"], objections:["Qualité du prof"],bien:["Pitch produit"],      bloque:["Gestion objection qualité"],confiance:5,suggestions:""},
  {id:3,date:"2026-04-01",auteur:"Julien",  anonyme:false,clientTypes:["Parent pressé"],    objections:["Je dois réfléchir"],bien:["Closing"],           bloque:[],                           confiance:9,suggestions:"Le script de closing est très efficace."},
  {id:4,date:"2026-04-01",auteur:"Jonathan",anonyme:true, clientTypes:["Parent négociateur"],objections:["Prix","Concurrence"],bien:["Découverte client"],bloque:["Closing"],               confiance:4,suggestions:"Besoin d'un script pour deux objections simultanées."},
  {id:5,date:"2026-03-31",auteur:"Julien",  anonyme:false,clientTypes:["Parent stressé"],   objections:["Prix"],           bien:["Introduction"],       bloque:["Pitch trop long"],          confiance:6,suggestions:""},
];
export const INIT_MATCHINGS=[
  {id:1,date:"2026-04-02",auteur:"Julien",  idealTyp:"Étudiant grande école",chosenTyp:"Étudiant grande école",followed:true, niveau:"Lycée général",psycho:"Compétiteur / Haut Potentiel"},
  {id:2,date:"2026-04-02",auteur:"Jonathan",idealTyp:"Professeur EN",        chosenTyp:"Étudiant université",  followed:false,niveau:"Collège",      psycho:"Stressé / Anxieux"},
  {id:3,date:"2026-04-01",auteur:"Julien",  idealTyp:"Étudiant grande école",chosenTyp:"Étudiant grande école",followed:true, niveau:"Prépa",       psycho:"Compétiteur / Haut Potentiel"},
  {id:4,date:"2026-04-01",auteur:"Jonathan",idealTyp:"AESH",                 chosenTyp:"Professeur EN",        followed:false,niveau:"Collège",      psycho:"Stressé / Anxieux"},
  {id:5,date:"2026-03-31",auteur:"Julien",  idealTyp:"Étudiant université",  chosenTyp:"Étudiant université",  followed:true, niveau:"Primaire",     psycho:"Introverti / Réservé"},
];
export const INIT_DEMANDES=[
  {id:1,date:"2026-04-02",auteur:"Julien",  cp:"92200",ville:"Neuilly",      matieres:["Maths"],    niveau:"Lycée général",typo:["Étudiant grande école"]},
  {id:2,date:"2026-04-01",auteur:"Jonathan",cp:"75016",ville:"Paris 16e",    matieres:["Français"], niveau:"Collège",      typo:["Professeur EN"]},
  {id:3,date:"2026-04-01",auteur:"Julien",  cp:"69006",ville:"Lyon",         matieres:["Maths"],    niveau:"Prépa",        typo:["Étudiant grande école"]},
  {id:4,date:"2026-03-31",auteur:"Jonathan",cp:"13008",ville:"Marseille",    matieres:["Anglais"],  niveau:"Lycée général", typo:["Étudiant université"]},
];
export const INIT_RENTREE=[
  {id:1,date:"2026-04-02",auteur:"Julien",  famille:"Dupont", classe:"Terminale",    matieres:["Maths","Physique"],        rappel:"2026-08-15",notes:"Budget validé"},
  {id:2,date:"2026-04-01",auteur:"Jonathan",famille:"Leclerc",classe:"5ème",         matieres:["Français"],                rappel:"2026-07-01",notes:""},
  {id:3,date:"2026-04-01",auteur:"Julien",  famille:"Petit",  classe:"2ème prépa",   matieres:["Maths","Physique","Chimie"],rappel:"2026-08-01",notes:"Déjà client"},
  {id:4,date:"2026-03-31",auteur:"Jonathan",famille:"Bernard",classe:"CE2",          matieres:["Maths","Français"],        rappel:"2026-07-15",notes:"Enfant DYS"},
];
export const INIT_SUGGESTIONS=[
  {id:1,date:"2026-04-02",auteur:"Julien",  type:"objection",contenu:"Ajouter réponse à 'Je vais d'abord essayer avec mon enfant'",statut:"pending"},
  {id:2,date:"2026-04-01",auteur:"Jonathan",type:"script",   contenu:"Script closing pour parents comparant avec Superprof",statut:"pending"},
];
export const FORMATION_DEFAULT={
  sales:{title:"Expertise Sales",icon:"📞",color:"#16A34A",modules:[{id:1,title:"Fondamentaux de la vente",duration:"45 min",done:false,score:null,description:"Les bases de la persuasion et du cycle de vente Sherpas",objectives:["Comprendre les principes fondamentaux de la vente consultative","Maîtriser le cycle de vente Sherpas en 4 phases","Identifier les leviers psychologiques de la décision parentale","Adapter son discours au profil du parent"],content:[
{type:"text",title:"Étape 1 — La vente consultative",body:"Bienvenue dans le premier module de formation Sherpas.\n\nChez Les Sherpas, on ne vend pas un produit — on prescrit une solution éducative.\n\nLa vente consultative repose sur 3 piliers fondamentaux :\n\n1. L'ÉCOUTE ACTIVE\nComprendre le besoin réel du parent avant de proposer quoi que ce soit. Un parent qui appelle a un problème précis — ton rôle est de le faire parler.\n\n2. LA PRESCRIPTION\nRecommander le bon profil de prof comme un médecin prescrit un traitement. Tu ne proposes pas « un prof de maths » — tu prescris « un étudiant en école d'ingénieurs, mentor d'excellence, qui va challenger votre fils en Terminale S ».\n\n3. LA CONFIANCE\nLe parent doit sentir qu'on agit dans l'intérêt de son enfant, pas pour faire du chiffre. C'est cette confiance qui transforme un prospect en client fidèle.\n\nLa grande différence avec la vente classique : on ne pousse pas un produit, on tire le besoin vers la solution.",quiz:[{question:"Quel est le premier pilier de la vente consultative chez Sherpas ?",choices:["La négociation du prix","L'écoute active","La présentation du catalogue"],correctIndex:1,explanation:"L'écoute active est le fondement : comprendre le besoin avant de proposer."},{question:"Comment doit-on présenter un professeur au parent ?",choices:["Comme un produit avec des caractéristiques techniques","Comme une prescription adaptée au profil de l'enfant","Comme le moins cher du marché"],correctIndex:1,explanation:"On prescrit une solution personnalisée, pas un produit générique."}]},
{type:"text",title:"Étape 2 — Le pitch Sherpas en 60 secondes",body:"Avant de détailler le cycle de vente, il faut maîtriser le pitch Sherpas. Tu dois pouvoir le réciter en 60 secondes :\n\n« Les Sherpas, c'est la plateforme de cours particuliers qui met en relation votre enfant avec des professeurs triés sur le volet.\n\nNos profs sont sélectionnés à moins de 5% — des étudiants de grandes écoles, des professeurs certifiés, des spécialistes.\n\nLa différence ? On ne vous propose pas juste un prof de maths. On analyse le profil de votre enfant — son niveau, sa personnalité, ses objectifs — et on prescrit LE profil qui va lui correspondre.\n\nCompatibilité garantie : si ça ne matche pas, on change gratuitement. »\n\nÉléments clés du pitch :\n- Sélection < 5% (crédibilité)\n- Prescription personnalisée (différenciation)\n- Garantie de compatibilité (réassurance)\n- Des milliers de familles accompagnées (preuve sociale)",quiz:[{question:"Quel est le taux de sélection des profs Sherpas à mentionner ?",choices:["Moins de 20%","Moins de 10%","Moins de 5%"],correctIndex:2,explanation:"Moins de 5% — c'est l'argument de crédibilité principal du pitch."}]},
{type:"text",title:"Étape 3 — Les 4 phases du cycle de vente",body:"Chaque appel Sherpas suit un cycle précis en 4 phases. Respecte cet ordre — ne saute JAMAIS une étape.\n\n━━━ PHASE 1 — INTRODUCTION (2 min) ━━━\nObjectif : créer le lien et poser le cadre.\n« Bonjour [Prénom], c'est [Ton prénom] des Sherpas. Avez-vous deux minutes ? »\nClés : sourire vocal, énergie positive, légitimité immédiate.\nErreur fatale : parler du produit dès les premières secondes.\n\n━━━ PHASE 2 — DÉCOUVERTE (8-10 min) ━━━\nObjectif : comprendre la situation en profondeur.\nMéthode SPIN :\n  S — Situation : « En quelle classe est votre enfant ? »\n  P — Problème : « Depuis quand ces difficultés ? »\n  I — Implication : « Est-ce que ça impacte sa confiance ? »\n  N — Need-payoff : « Qu'aimeriez-vous voir changer ? »\nClé : poser des questions ouvertes, reformuler, ne JAMAIS pitcher avant d'avoir compris.\n\n━━━ PHASE 3 — PRESCRIPTION (5-7 min) ━━━\nObjectif : recommander le bon profil avec des arguments personnalisés.\nOutil : Lanterne V5 — Dual Path (Idéal algorithmique vs Choix manuel).\nTechnique : Feature-to-Benefit — transformer les caractéristiques du prof en bénéfices pour l'enfant.\nExemple : « Un étudiant en école d'ingénieurs qui a réussi les concours il y a 2 ans — il connaît exactement les pièges du programme de votre fils. »\n\n━━━ PHASE 4 — CLOSING (3-5 min) ━━━\nObjectif : obtenir l'engagement.\nTechniques :\n  - Closing assumptif : « Je vous propose une mise en relation dès cette semaine. »\n  - Reformulation : « Si je résume, vous cherchez... c'est bien ça ? »\n  - Dernière objection : « Qu'est-ce qui vous empêche de vous lancer aujourd'hui ? »\nClé : accompagner vers la décision, ne jamais forcer.",quiz:[{question:"Combien de phases comporte le cycle de vente Sherpas ?",choices:["3 phases","4 phases","5 phases"],correctIndex:1,explanation:"4 phases : Introduction, Découverte, Prescription, Closing."},{question:"Que signifie le 'I' dans la méthode SPIN ?",choices:["Introduction","Implication","Information"],correctIndex:1,explanation:"Implication — faire prendre conscience de l'impact du problème."},{question:"À quel moment utilise-t-on la Lanterne V5 ?",choices:["En introduction","En découverte","En prescription"],correctIndex:2,explanation:"La Lanterne V5 est l'outil de la phase Prescription pour recommander le bon profil."}]},
{type:"exercise",title:"Étape 4 — Simulation d'appel",body:"C'est le moment de pratiquer. Réalise cette simulation seul ou en binôme.\n\n━━━ CONSIGNE ━━━\nSimule un appel complet de 15 minutes en suivant les 4 phases.\n\nSi tu es seul : récite à voix haute chaque phase en imaginant les réponses du parent.\nSi tu es en binôme :\n  Rôle 1 — Le Sales : suis les 4 phases du cycle\n  Rôle 2 — Le parent : profil « Parent stressé », objection « C'est trop cher »\n\n━━━ CHECKLIST D'AUTO-ÉVALUATION ━━━\nCoche chaque point que tu as réussi :\n\n□ Introduction < 2 min, avec sourire vocal\n□ Au moins 4 questions de découverte posées (SPIN)\n□ Reformulation du besoin AVANT le pitch\n□ Utilisation du Feature-to-Benefit (pas de jargon)\n□ Mention du taux de sélection < 5%\n□ Gestion de l'objection prix avec l'argument ROI\n□ Closing doux avec proposition de rappel\n□ Durée totale entre 12 et 18 minutes\n\n━━━ DÉBRIEF ━━━\nAprès la simulation, note :\n- Ce qui a bien fonctionné :\n- Ce qui t'a bloqué :\n- Ce que tu feras différemment la prochaine fois :"},
{type:"checklist",title:"Étape 5 — Points clés à retenir",body:"Avant de passer au quiz final, assure-toi de maîtriser ces fondamentaux :\n\n✅ La vente consultative = écoute + prescription + confiance\n✅ Ne JAMAIS pitcher avant la phase 3 (Découverte d'abord)\n✅ Méthode SPIN : Situation → Problème → Implication → Need-payoff\n✅ Lanterne V5 = outil de prescription Dual Path\n✅ Feature-to-Benefit : transformer une caractéristique en bénéfice concret\n✅ Sélection < 5% = argument de crédibilité principal\n✅ Closing = accompagnement, pas pression\n✅ Chaque appel = 1 feedback dans le Sales Center\n✅ Compatibilité garantie = argument de réassurance\n✅ Reformuler avec les mots du parent, pas les tiens"},
{type:"quiz",title:"Étape 6 — Quiz final",body:"Dernière étape : le quiz récapitulatif.\n\nCe quiz couvre tout le module. Tu dois obtenir au moins 4/5 pour valider.\nTon score final sera calculé sur l'ensemble des quiz du module.",quiz:[{question:"Un parent appelle et dit « Je cherche un prof de maths pour mon fils en Terminale ». Quelle est ta première réaction ?",choices:["Proposer immédiatement un étudiant en école d'ingénieurs","Poser des questions pour comprendre la situation (SPIN)","Donner le prix des cours"],correctIndex:1,explanation:"Toujours commencer par la découverte — comprendre avant de prescrire."},{question:"Quelle est la bonne façon de présenter un prof Sherpas ?",choices:["« On a des profs de maths à partir de 25€/h »","« Un étudiant à Centrale qui a réussi le même concours que votre fils vise — il sait exactement quoi travailler »","« On a 500 profs disponibles, choisissez celui que vous voulez »"],correctIndex:1,explanation:"Feature-to-Benefit : on personnalise l'argument en fonction du profil de l'enfant."},{question:"Un parent dit « C'est trop cher ». Quelle technique utilises-tu ?",choices:["Proposer une réduction immédiate","Comparer le coût au résultat (ROI) et reformuler l'objection","Dire que c'est le prix du marché"],correctIndex:1,explanation:"Reformulation + argument ROI : « Si votre enfant passe de 8 à 14, qu'est-ce que ça vaut ? »"},{question:"Dans quel ordre se déroulent les 4 phases ?",choices:["Découverte → Introduction → Closing → Prescription","Introduction → Découverte → Prescription → Closing","Introduction → Prescription → Découverte → Closing"],correctIndex:1,explanation:"Introduction → Découverte → Prescription → Closing. Ne jamais sauter d'étape."},{question:"Pourquoi remplir un feedback après chaque appel dans le Sales Center ?",choices:["Pour que le manager puisse surveiller","Pour améliorer ses performances et aider l'équipe à progresser","Ce n'est pas obligatoire"],correctIndex:1,explanation:"Le feedback est un outil de progression individuelle ET collective."}]}
]},{id:2,title:"Découverte client — SPIN",duration:"60 min",done:true,score:85,description:"Méthode SPIN : Situation, Problème, Implication, Need-payoff"},{id:3,title:"Cycle de vente Sherpas",duration:"35 min",done:false,description:"Comprendre le tunnel de vente de l'appel au closing"},{id:4,title:"Techniques de closing",duration:"40 min",done:false,description:"Closing assumptif, doux, récapitulatif"}]},
  education:{title:"Secteur Éducation",icon:"🏫",color:"#0B68B4",modules:[{id:5,title:"Le système scolaire français",duration:"45 min",done:false,description:"De la maternelle au bac : programmes, enjeux, acteurs"},{id:6,title:"DYS, TDAH — troubles d'apprentissage",duration:"50 min",done:false,description:"Identifier et accompagner les profils atypiques"},{id:7,title:"Profils psychologiques élèves",duration:"40 min",done:false,description:"Les 4 profils de la Lanterne : introverti, décrocheur, compétiteur, stressé"},{id:8,title:"La Prépa — codes et attentes",duration:"35 min",done:false,description:"MPSI, PCSI, ECG : comprendre pour mieux prescrire"}]},
  argumentaires:{title:"Argumentaires V5",icon:"💡",color:"#DA4F00",modules:[{id:9,title:"Feature-to-Benefit : vendre les profils",duration:"55 min",done:false,description:"Transformer les caractéristiques d'un prof en bénéfices concrets"},{id:10,title:"Maîtriser la Matrice Dual Path",duration:"60 min",done:false,description:"Quand suivre l'idéal Matrice, quand pivoter"},{id:11,title:"Recadrer les attentes parentales",duration:"45 min",done:false,description:"Gérer les demandes irréalistes avec confiance et pédagogie"}]},
  neuro:{title:"Profils Neuroatypiques",icon:"🧠",color:"#7C3AED",modules:[{id:101,title:"Introduction aux profils neuroatypiques",duration:"40 min",done:false,description:"TDAH, TSA, DYS, HPI — comprendre les bases neurologiques et les impacts sur l'apprentissage"},{id:102,title:"TDAH — Accompagner l'attention",duration:"45 min",done:false,description:"Techniques pour maintenir l'attention, adapter le rythme, gérer l'impulsivité en cours"},{id:103,title:"TSA — Communiquer autrement",duration:"50 min",done:false,description:"Communication explicite, rituels prévisibles, gestion sensorielle"},{id:104,title:"DYS — Outils de compensation",duration:"45 min",done:false,description:"Dyslexie, dysorthographie, dyspraxie — adaptations pédagogiques concrètes"},{id:105,title:"HPI — Stimuler sans surcharger",duration:"40 min",done:false,description:"Double exceptionnalité, ennui scolaire, gestion émotionnelle du haut potentiel"},{id:106,title:"Profils complexes — Multi-troubles",duration:"55 min",done:false,description:"Quand plusieurs troubles coexistent : lecture globale et stratégie d'accompagnement"},{id:107,title:"Utiliser la Matrice Neuro en appel",duration:"50 min",done:false,description:"Simulation : prescrire le bon profil prof pour chaque trouble, argumenter avec les parents"}]},
};
