export const NEURO_PROFS=["Psychologue","Prof EN Psychopédagogie","Professeur EN classique","AESH / AVS","Étudiant en Psychologie"];
export const NEURO_TROUBLES=["TDAH","TSA","DYS","HPI","Multi-dys / profil complexe"];
export const NEURO_COLORS={TDAH:"#0B68B4",TSA:"#7C3AED",DYS:"#DA4F00",HPI:"#D97706","Multi-dys / profil complexe":"#E11D48"};
export const NEURO_EMOJIS={TDAH:"⚡",TSA:"🧩",DYS:"📖",HPI:"🌟","Multi-dys / profil complexe":"🔀"};

export const NEURO_MATRIX=[
  // ── PSYCHOLOGUE ──────────────────────────────────────────────────
  {prof:"Psychologue",trouble:"TDAH",badge:"ideal",
   realite:"Le psychologue comprend les mécanismes neurobiologiques du TDAH et peut adapter chaque séance en temps réel selon l'état attentionnel de l'élève.",
   appel:"'Notre psychologue ne fait pas que 'gérer' le TDAH — il comprend pourquoi votre enfant est comme il est, et il construit chaque séance autour de ça. Ce n'est pas du rattrapage, c'est de la pédagogie sur mesure.'"},
  {prof:"Psychologue",trouble:"TSA",badge:"ideal",
   realite:"Formé aux troubles envahissants du développement, le psychologue sait créer l'environnement prévisible et structuré dont l'élève TSA a besoin pour apprendre.",
   appel:"'Votre enfant a besoin d'un cadre très précis pour être à l'aise. Notre psychologue sait exactement comment le créer — même à distance, même la première séance.'"},
  {prof:"Psychologue",trouble:"DYS",badge:"acceptable",
   realite:"Le psychologue comprend les mécanismes des troubles DYS mais n'est pas spécialiste de la pédagogie adaptée. Son apport est fort sur le plan émotionnel, moins sur les outils concrets.",
   appel:"'Pour la DYS, notre psychologue est excellent pour travailler la confiance en soi et le rapport à l'échec — qui sont souvent le vrai frein. Sur les outils pédagogiques, on le pair avec un spécialiste si besoin.'"},
  {prof:"Psychologue",trouble:"HPI",badge:"ideal",
   realite:"Le psychologue est particulièrement adapté au HPI : il comprend la double exceptionnalité, gère la dysharmonie développementale et sait stimuler sans surcharger.",
   appel:"'Un enfant HPI ne souffre pas d'un manque — il souffre d'un décalage. Notre psychologue comprend ça. Il va travailler l'intelligence émotionnelle autant que le potentiel intellectuel.'"},
  {prof:"Psychologue",trouble:"Multi-dys / profil complexe",badge:"ideal",
   realite:"Face à un profil complexe, le psychologue est le seul profil capable d'une lecture globale — cognitive, émotionnelle et comportementale — sans réduire l'élève à une seule étiquette.",
   appel:"'Quand un enfant a plusieurs troubles à la fois, il faut quelqu'un qui voit le tableau complet. Notre psychologue, c'est exactement ça — un chef d'orchestre qui comprend chaque instrument.'"},

  // ── PROF EN PSYCHOPÉDAGOGIE ──────────────────────────────────────
  {prof:"Prof EN Psychopédagogie",trouble:"TDAH",badge:"ideal",
   realite:"La double formation pédagogie + psychologie en fait le profil le plus complet : il sait à la fois adapter les exercices ET comprendre les dynamiques attentionnelles.",
   appel:"'Ce profil, c'est le meilleur des deux mondes — un vrai prof qui sait faire cours, et quelqu'un qui comprend précisément pourquoi votre enfant décroche. C'est rare, et c'est ce dont il a besoin.'"},
  {prof:"Prof EN Psychopédagogie",trouble:"TSA",badge:"acceptable",
   realite:"Sa formation lui donne les bases théoriques, mais la pratique avec TSA est très variable. Certains excellents, d'autres démunis. Il faut vérifier son expérience concrète.",
   appel:"'Notre prof en psychopédagogie a les outils pour accompagner votre enfant, mais je veux être honnête : je vais m'assurer qu'il a une vraie expérience avec le TSA avant de vous le proposer.'"},
  {prof:"Prof EN Psychopédagogie",trouble:"DYS",badge:"ideal",
   realite:"C'est le profil de référence pour la DYS. Il connaît les outils de compensation, les adaptations pédagogiques officielles et sait travailler en lien avec les bilans orthophoniques.",
   appel:"'Pour la dyslexie, la dysorthographie ou la dyspraxie, ce profil est vraiment notre expert. Il ne va pas juste 'faire avec' les difficultés — il a des méthodes conçues spécifiquement pour les contourner.'"},
  {prof:"Prof EN Psychopédagogie",trouble:"HPI",badge:"ideal",
   realite:"Formé à la double exceptionnalité HPI + DYS, il comprend les paradoxes du HPI (très fort / très fragile) et sait adapter son niveau sans ennuyer ni surcharger.",
   appel:"'Un enfant HPI peut être brillant et en grande difficulté en même temps. Notre prof en psychopédagogie comprend cette contradiction — et il sait précisément comment y répondre.'"},
  {prof:"Prof EN Psychopédagogie",trouble:"Multi-dys / profil complexe",badge:"ideal",
   realite:"C'est le profil idéal pour les cas complexes : il lit plusieurs troubles simultanément, adapte en continu et comprend les interactions entre les différents déficits.",
   appel:"'Quand le bilan révèle plusieurs troubles qui s'additionnent, il faut quelqu'un de très spécialisé. Notre prof en psychopédagogie, c'est précisément sa spécialité — les profils qu'on ne sait pas comment aborder.'"},

  // ── PROFESSEUR EN CLASSIQUE ──────────────────────────────────────
  {prof:"Professeur EN classique",trouble:"TDAH",badge:"acceptable",
   realite:"Sa pédagogie structurée peut aider, mais sans formation aux troubles attentionnels, il risque de mal interpréter l'agitation ou l'oubli comme du manque de volonté.",
   appel:"'Notre professeur certifié a une vraie rigueur pédagogique qui peut aider à structurer votre enfant. Je serai transparent : il n'est pas spécialisé TDAH, mais on peut lui demander de s'adapter au rythme de votre enfant.'"},
  {prof:"Professeur EN classique",trouble:"TSA",badge:"deconseille",
   realite:"Sans formation spécifique au TSA, il risque de créer des situations d'incompréhension mutuelle. Les codes implicites de la communication scolaire classique ne fonctionnent pas avec le TSA.",
   appel:"'Soyons honnêtes : pour un profil TSA, un professeur classique sans formation spécifique, ce n'est pas le bon choix. Je préfère vous orienter vers quelqu'un de vraiment adapté plutôt que de prendre un risque.'"},
  {prof:"Professeur EN classique",trouble:"DYS",badge:"acceptable",
   realite:"Il peut adapter en surface (agrandir les textes, donner plus de temps) mais sans connaître les mécanismes DYS profonds, ses adaptations restent insuffisantes pour un trouble sévère.",
   appel:"'Notre professeur peut adapter ses supports et son rythme. Pour une DYS légère à modérée, ça fonctionne bien. Pour un cas plus sévère, je préférerais vous proposer un spécialiste — mais soyons pragmatiques d'abord.'"},
  {prof:"Professeur EN classique",trouble:"HPI",badge:"acceptable",
   realite:"Il peut stimuler un HPI intellectuellement, mais risque de mal gérer l'ennui, l'insolence apparente ou les questions déstabilisantes. La relation peut vite devenir tendue.",
   appel:"'Un professeur certifié peut vraiment nourrir la curiosité d'un enfant HPI sur le contenu. Le défi, c'est la relation — mais avec les bons repères, ça peut très bien se passer.'"},
  {prof:"Professeur EN classique",trouble:"Multi-dys / profil complexe",badge:"deconseille",
   realite:"Un profil multi-dys requiert des adaptations simultanées sur plusieurs axes. Sans formation spécialisée, le prof classique ne peut pas gérer cette complexité sans mettre l'élève en échec.",
   appel:"'Je vais être direct : pour un profil aussi complexe, ce n'est pas le bon match. Je préfère prendre le temps de trouver le bon profil plutôt que de vous proposer quelqu'un qui ne pourra pas répondre aux besoins réels.'"},

  // ── AESH / AVS ───────────────────────────────────────────────────
  {prof:"AESH / AVS",trouble:"TDAH",badge:"ideal",
   realite:"L'AESH est formé à l'accompagnement de proximité, à la gestion des impulsions et à la régulation émotionnelle. C'est le profil le plus adapté pour soutenir sans surcharger.",
   appel:"'Notre AESH ne fait pas cours — il accompagne. Pour un enfant TDAH, c'est souvent ce dont il a besoin : quelqu'un qui l'aide à rester ancré dans la tâche, qui ne juge pas, qui relance sans pression.'"},
  {prof:"AESH / AVS",trouble:"TSA",badge:"ideal",
   realite:"L'AESH est le profil de référence pour le TSA. Formé à l'accompagnement individuel, il connaît les rituels, la gestion sensorielle et les techniques de communication alternative.",
   appel:"'Pour votre enfant, la priorité c'est que quelqu'un comprenne son mode de fonctionnement et s'y adapte — pas l'inverse. Notre AESH fait exactement ça. Chaque séance est construite autour de lui.'"},
  {prof:"AESH / AVS",trouble:"DYS",badge:"acceptable",
   realite:"L'AESH apporte une présence rassurante et peut aider à la mise en travail, mais son expertise pédagogique sur la DYS est variable. L'apport est surtout comportemental et émotionnel.",
   appel:"'Notre AESH va vraiment aider votre enfant à se mettre au travail sans se bloquer sur ses difficultés. Pour les outils pédagogiques spécifiques à la DYS, on peut combiner avec un spécialiste matière si besoin.'"},
  {prof:"AESH / AVS",trouble:"HPI",badge:"deconseille",
   realite:"Le HPI a besoin de stimulation intellectuelle intense. L'AESH n'est pas formé pour ça — et un enfant HPI risque de s'ennuyer et de décrocher encore plus vite.",
   appel:"'Pour un enfant HPI, l'enjeu c'est le défi intellectuel. L'AESH n'est pas le bon profil ici — je veux lui trouver quelqu'un qui peut vraiment le nourrir sur le plan cognitif.'"},
  {prof:"AESH / AVS",trouble:"Multi-dys / profil complexe",badge:"ideal",
   realite:"L'AESH est formé à l'adaptation continue et à la flexibilité. Face à un profil complexe, il ajuste séance par séance sans chercher à 'normaliser' l'élève.",
   appel:"'Notre AESH n'a pas de méthode rigide — il s'adapte à l'enfant tel qu'il est ce jour-là. Pour un profil complexe qui change d'une semaine à l'autre, c'est précisément ce qu'il faut.'"},

  // ── ÉTUDIANT EN PSYCHOLOGIE ──────────────────────────────────────
  {prof:"Étudiant en Psychologie",trouble:"TDAH",badge:"acceptable",
   realite:"Il a les bases théoriques et une vraie empathie, mais son expérience pratique est limitée. Il peut être très efficace si le TDAH n'est pas sévère et si la relation est bonne.",
   appel:"'Notre étudiant en psychologie comprend le TDAH — pas seulement en théorie, mais il sait pourquoi votre enfant fonctionne comme il fonctionne. Et souvent, cette compréhension change tout à la relation.'"},
  {prof:"Étudiant en Psychologie",trouble:"TSA",badge:"deconseille",
   realite:"Malgré sa formation théorique, un étudiant manque d'expérience pratique pour gérer les particularités sensorielles, les crises et la communication atypique du TSA.",
   appel:"'Je vais être honnête avec vous : pour un profil TSA, j'ai besoin de vous proposer quelqu'un avec plus d'expérience pratique. Ce n'est pas une question de compétence — c'est une question de ce que votre enfant mérite.'"},
  {prof:"Étudiant en Psychologie",trouble:"DYS",badge:"acceptable",
   realite:"Sa formation lui donne une bonne lecture des mécanismes DYS et une empathie réelle. Ses outils pédagogiques sont moins rodés, mais son approche bienveillante peut débloquer la confiance.",
   appel:"'Notre étudiant comprend les mécanismes de la dyslexie et ne va surtout pas mettre votre enfant en difficulté. Sa force, c'est qu'il ne va pas le braquer — et souvent, c'est ça le premier pas.'"},
  {prof:"Étudiant en Psychologie",trouble:"HPI",badge:"ideal",
   realite:"La proximité générationnelle combinée à sa formation en psychologie en fait un profil excellent pour le HPI : il peut tenir le rythme intellectuel et comprendre les enjeux émotionnels du profil.",
   appel:"'Un enfant HPI a besoin de quelqu'un qui le suit vraiment sur le plan intellectuel et qui comprend pourquoi être très intelligent peut aussi être très difficile. Notre étudiant en psychologie, c'est exactement ce profil-là.'"},
  {prof:"Étudiant en Psychologie",trouble:"Multi-dys / profil complexe",badge:"deconseille",
   realite:"Un profil complexe requiert une expertise clinique confirmée. L'étudiant, même motivé, n'a pas encore les outils pour naviguer la complexité des interactions entre les différents troubles.",
   appel:"'Pour un profil aussi complexe, je dois vous proposer quelqu'un avec plus d'expérience. Je préfère prendre le temps de bien choisir plutôt que de vous orienter vers quelqu'un qui ne pourra pas être à la hauteur de la situation.'"},
];
