export const NEURO_PROFS=["Psychologue","Prof EN Psychopédagogie","Professeur EN classique","AESH / AVS","Étudiant en Psychologie"];
export const NEURO_TROUBLES=["TDAH","TSA","DYS","HPI","Multi-dys / profil complexe"];
export const NEURO_COLORS={TDAH:"#0B68B4",TSA:"#7C3AED",DYS:"#DA4F00",HPI:"#D97706","Multi-dys / profil complexe":"#E11D48"};
export const NEURO_EMOJIS={TDAH:"⚡",TSA:"🧩",DYS:"📖",HPI:"🌟","Multi-dys / profil complexe":"🔀"};

export const NEURO_MATRIX=[
  // ── PSYCHOLOGUE ──────────────────────────────────────────────────
  {prof:"Psychologue",trouble:"TDAH",badge:"acceptable",
   realite:"Il comprend les mécanismes de l'attention et de l'impulsivité, mais son approche reste davantage thérapeutique que pédagogique — il traite le symptôme plus que le retard scolaire.",
   appel:"Ce qui est rare avec ce profil, c'est qu'il ne va pas juste gérer le cours — il va comprendre pourquoi votre enfant décroche, et travailler dessus directement pendant la séance."},
  {prof:"Psychologue",trouble:"TSA",badge:"ideal",
   realite:"Il connaît le spectre autistique mais n'est pas nécessairement formé aux adaptations pédagogiques concrètes qu'exige le quotidien scolaire d'un enfant TSA.",
   appel:"Avec un enfant TSA, ce qui change tout c'est la relation. Et lui, il sait exactement comment créer cette relation-là, sans forcer, sans brusquer — c'est son métier."},
  {prof:"Psychologue",trouble:"DYS",badge:"acceptable",
   realite:"Les troubles DYS relèvent davantage de la remédiation cognitive que de la psychologie — son regard est utile mais pas toujours opérationnel sur les outils concrets.",
   appel:"Si votre enfant évite les devoirs parce qu'il a peur d'échouer encore, là c'est plus juste une question de méthode — c'est une question de confiance. Et c'est exactement ce sur quoi il travaille."},
  {prof:"Psychologue",trouble:"HPI",badge:"acceptable",
   realite:"Le HPI ne se traite pas, il se comprend — le psychologue aide à décrypter le profil mais n'apporte pas la stimulation intellectuelle que cherche l'enfant.",
   appel:"Souvent avec les HPI, le problème c'est pas le niveau, c'est le sens. Pourquoi travailler si tout est trop facile ou trop absurde ? Lui, il sait répondre à cette question-là."},
  {prof:"Psychologue",trouble:"Multi-dys / profil complexe",badge:"ideal",
   realite:"Précieux pour déchiffrer l'ensemble du tableau, mais insuffisant seul si les lacunes scolaires sont importantes.",
   appel:"Quand il y a plusieurs choses qui se cumulent, les familles ont souvent l'impression que personne ne comprend vraiment le tableau complet. Lui, c'est précisément ce qu'il fait — il tient l'ensemble."},

  // ── PROF EN PSYCHOPÉDAGOGIE ──────────────────────────────────────
  {prof:"Prof EN Psychopédagogie",trouble:"TDAH",badge:"ideal",
   realite:"C'est le profil le plus équipé pour adapter le rythme et fragmenter les tâches — mais il reste un enseignant, pas un thérapeute.",
   appel:"Ce qui est bien avec lui, c'est qu'il connaît le programme ET il sait adapter — votre enfant avance sur les matières sans que son attention devienne un mur à chaque séance."},
  {prof:"Prof EN Psychopédagogie",trouble:"TSA",badge:"acceptable",
   realite:"La psychopédagogie prépare mieux que l'enseignement classique, mais le TSA demande une formation spécifique que tous les profs psychopéda n'ont pas nécessairement.",
   appel:"Il structure ses séances de façon très prévisible, et c'est exactement ce dont un enfant TSA a besoin pour se sentir en sécurité et pouvoir apprendre sereinement."},
  {prof:"Prof EN Psychopédagogie",trouble:"DYS",badge:"ideal",
   realite:"C'est son terrain de prédilection — la psychopédagogie est née en partie pour répondre aux DYS. Il sait quoi faire, comment le faire, et pourquoi.",
   appel:"C'est vraiment son domaine de prédilection — il sait ce qui coince, pourquoi ça coince, et il a les outils concrets pour le corriger. C'est le profil le plus direct sur les DYS."},
  {prof:"Prof EN Psychopédagogie",trouble:"HPI",badge:"ideal",
   realite:"Le HPI a surtout besoin d'être challengé et de trouver du sens — la psychopédagogie répond bien à ça, même si un enfant très avancé peut parfois dépasser le prof sur le fond.",
   appel:"Il ne va pas juste faire le cours — il va comprendre pourquoi votre enfant s'ennuie et retravailler le rapport à l'apprentissage. C'est souvent le déclic qui manquait."},
  {prof:"Prof EN Psychopédagogie",trouble:"Multi-dys / profil complexe",badge:"ideal",
   realite:"C'est le profil le plus polyvalent — il ne paniquera pas et aura des outils pour la plupart des configurations, même si certains cas très lourds dépassent son périmètre.",
   appel:"Ce type de profil a besoin de quelqu'un qui s'adapte en temps réel sans perdre de vue les objectifs scolaires. C'est exactement ce qu'il sait faire, même quand c'est complexe."},

  // ── PROFESSEUR EN CLASSIQUE ──────────────────────────────────────
  {prof:"Professeur EN classique",trouble:"TDAH",badge:"acceptable",
   realite:"Formé pour enseigner à un groupe, il n'a pas naturellement les réflexes d'adaptation nécessaires quand l'attention décroche toutes les dix minutes.",
   appel:"Si le trouble est léger et que l'enfant a surtout besoin de combler des lacunes, un prof solide sur le programme qui tient un cadre clair — c'est parfois ce qui marche le mieux."},
  {prof:"Professeur EN classique",trouble:"TSA",badge:"deconseille",
   realite:"Non formé à la communication atypique propre au TSA, il risque de mal interpréter les comportements de l'enfant et de créer de la friction sans le vouloir.",
   appel:"Pour un profil Asperger très scolaire, intellectuellement curieux et à l'aise en interaction duelle, la rigueur et l'expertise d'un prof de l'EN devient une vraie source de stimulation et de fierté."},
  {prof:"Professeur EN classique",trouble:"DYS",badge:"acceptable",
   realite:"Sans formation spécifique, il a tendance à percevoir les erreurs comme un manque de travail plutôt qu'un trouble — ce qui peut être destructeur pour l'estime de soi.",
   appel:"Pour un DYS bien compensé dont la famille cherche avant tout à combler des lacunes académiques, sa maîtrise du programme et son exigence bienveillante ont une valeur directe sur les résultats."},
  {prof:"Professeur EN classique",trouble:"HPI",badge:"ideal",
   realite:"Il connaît son programme — et un HPI qui s'ennuie a justement besoin de quelqu'un qui peut aller plus loin et plus vite que le cours standard.",
   appel:"Votre enfant a besoin de quelqu'un qui peut aller aussi vite et aussi loin que lui — un prof de l'EN qui maîtrise sa matière, c'est l'un des rares profils qui peut vraiment le challenger."},
  {prof:"Professeur EN classique",trouble:"Multi-dys / profil complexe",badge:"deconseille",
   realite:"Il n'a pas les outils pour adapter et risque de se concentrer sur le contenu au détriment du rythme de l'enfant — il sera dépassé.",
   appel:"Si la prise en charge globale est déjà bien en place par ailleurs, avoir quelqu'un de très solide sur les contenus académiques peut faire une vraie différence sur les résultats scolaires concrets."},

  // ── AESH / AVS ───────────────────────────────────────────────────
  {prof:"AESH / AVS",trouble:"TDAH",badge:"ideal",
   realite:"Il connaît le TDAH de l'intérieur et accompagne ces enfants au quotidien — mais il n'est pas enseignant, et sa capacité à faire progresser sur le programme reste limitée.",
   appel:"Il accompagne des enfants TDAH au quotidien — il sait exactement comment reprendre l'attention sans braquer l'enfant, et maintenir un rythme de travail sans que ça devienne une source de conflit."},
  {prof:"AESH / AVS",trouble:"TSA",badge:"ideal",
   realite:"C'est son terrain quotidien, mais tous les AESH n'ont pas le même niveau d'expérience avec le TSA — la qualité dépend fortement du profil individuel.",
   appel:"Ce qu'il apporte, c'est une connaissance du terrain que personne d'autre n'a vraiment. Il connaît ces enfants de l'intérieur — il sait ce qui rassure, ce qui surcharge, et comment travailler avec ça."},
  {prof:"AESH / AVS",trouble:"DYS",badge:"acceptable",
   realite:"Habitué à accompagner des enfants DYS en classe, il n'est pas formé à la remédiation — il peut soutenir sans vraiment corriger les mécanismes défaillants.",
   appel:"Si votre enfant a besoin d'être accompagné pas à pas, sans pression, quelqu'un qui sait exactement comment avancer sans le mettre en difficulté — c'est vraiment le profil pour ça."},
  {prof:"AESH / AVS",trouble:"HPI",badge:"deconseille",
   realite:"Non formé pour stimuler intellectuellement un enfant en avance — la relation risque d'être déséquilibrée et l'enfant de s'ennuyer rapidement.",
   appel:"Si votre enfant cumule un HPI avec un autre trouble, là ce qui prime c'est la stabilité et le bien-être. Et sur ça, son expérience du terrain scolaire est un vrai atout."},
  {prof:"AESH / AVS",trouble:"Multi-dys / profil complexe",badge:"acceptable",
   realite:"Habitué aux profils complexes en classe, les gérer seul en tête-à-tête sans le filet de l'équipe pédagogique est une situation très différente.",
   appel:"Ce qu'il a que les autres n'ont pas, c'est une lecture très concrète de ces profils — pas théorique, terrain. Et souvent, c'est exactement ce qui fait la différence."},

  // ── ÉTUDIANT EN PSYCHOLOGIE ──────────────────────────────────────
  {prof:"Étudiant en Psychologie",trouble:"TDAH",badge:"acceptable",
   realite:"Il a les bases théoriques sur le TDAH mais peu d'expérience pratique — il comprend le trouble sans forcément savoir quoi faire quand l'enfant décroche en pleine séance.",
   appel:"Pour un ado TDAH qui résiste à l'autorité, sa proximité et sa posture non-professorale peuvent lever les blocages relationnels que tous les autres profils n'ont pas réussi à contourner."},
  {prof:"Étudiant en Psychologie",trouble:"TSA",badge:"deconseille",
   realite:"La théorie ne suffit pas avec le TSA — il faut une expérience terrain que l'étudiant n'a pas encore, et le risque d'impair relationnel est réel.",
   appel:"Pour un enfant TSA en début de suivi, dont la priorité est de créer un premier lien de confiance dans un cadre informel et sans pression, sa douceur et son écoute peuvent être le premier pas vers un accompagnement plus structuré."},
  {prof:"Étudiant en Psychologie",trouble:"DYS",badge:"acceptable",
   realite:"Il comprend les mécanismes des DYS mais n'a pas les outils de remédiation — il peut être patient et bienveillant sans réellement faire avancer l'enfant sur le fond.",
   appel:"Si votre enfant a surtout perdu confiance en lui, avoir quelqu'un de bienveillant, sans jugement, qui comprend ce qu'il vit — ça peut suffire à lui redonner l'envie d'essayer."},
  {prof:"Étudiant en Psychologie",trouble:"HPI",badge:"ideal",
   realite:"Si le HPI est très avancé, il risque de se sentir supérieur à l'étudiant et de ne pas adhérer au suivi — la crédibilité peut être un vrai problème.",
   appel:"Les HPI qui refusent le rapport prof-élève classique, souvent ce dont ils ont besoin c'est d'un échange d'égal à égal. Et ça, c'est exactement ce qu'il va leur offrir."},
  {prof:"Étudiant en Psychologie",trouble:"Multi-dys / profil complexe",badge:"deconseille",
   realite:"Un profil complexe nécessite des outils et de l'expérience que l'étudiant n'a pas — bonne volonté et empathie ne suffisent pas face à un tableau clinique chargé.",
   appel:"Quand un enfant a tout refusé jusqu'ici, parfois ce qu'il faut c'est quelqu'un qui crée un lien authentique avant tout. Et ça, c'est vraiment son point fort."},
];
